### ISSUE TITLE
Nice app!

### ISSUE THREAD

**Issue by brtkwr** [rabingaire/never_kill_your_time#3]
Although I am not so keen on so many exclamation marks everywhere!!!

**Comment by rabingaire** [comment]
Thank you very much. Code is too much manual, and if you have time you could contribute.

**Comment by nmunro** [comment]
Hey, I'm the one who gave you a suggestion for a json config file, if you have a road map, I'll happily help you achieve it.

**Comment by rabingaire** [comment]
@nmunro Thank you very much for your concern on this small Script. I am thinking of using python file handling to read and write from JSON and add some more methods for editing, updating and deleting from JSON. let me know what do you think about it :)

**Comment by nmunro** [comment]
@rabingaire Could you explain what you have in slightly more details?

You talk of wanting to read and write to json from inside your app, does that mean you want to build a small GUI to allow users to add/edit/delete tasks?

It's just not quite clear what exactly read and writing json might mean.

**Comment by rabingaire** [comment]
Not the GUI environment, but I was hoping if users were able to type `never_kill_your_time add_routine` than they are asked with a bunch of question and the input given by users in response are saved in a JSON file locally. Later,  on when the program runs back it will read from JSON file and show the message.
@nmunro

**Comment by nmunro** [comment]
Oh, yeah, that's certainly be doable and a good way to do it.

**Comment by rabingaire** [comment]
WOW !!! @tarunvelli Because of you :) This small script is becoming more useful and easier to use. Thank You very much :)

**Comment by tarunvelli** [comment]
@rabingaire hey welcome, just happy to help! :)

**Comment by tarunvelli** [comment]
@nmunro thanks for giving the json file idea and shedding light on best practices :) 
@rabingaire it was a fun project, im happy that i was able to contribute :)

**Comment by rabingaire** [comment]
Thank you @nmunro for your contribution and @tarunvelli you made this script useful and better Thank you very much :)
