### ISSUE TITLE
Update install file to copy json file into bin

### ISSUE THREAD

**Issue by tarunvelli** [rabingaire/never_kill_your_time#9]
Im guessing that you will have to copy the json file also into bin. Do update install.sh appropriately

**Comment by rabingaire** [comment]
```
Traceback (most recent call last):
  File "/bin/never_kill_your_time", line 37, in <module>
    json_data=open("routine.json").read()
IOError: [Errno 2] No such file or directory: 'routine.json'
```
I get this error when I try to run `never_kill_your_time` from a desktop (Note: I have already installed script on bin). I don't have an idea why is it showing this type of behavior. @tarunvelli

**Comment by tarunvelli** [comment]
This commit solves it, test it and if it works merge it. thanks for pointing it out!

**Comment by rabingaire** [comment]
Works yahoo :)
